# MPLAB IDE generated this makefile for use with GNU make.
# Project: psygsr.mcp
# Date: Sun Sep 09 12:36:46 2012

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

psygsr.cof : Objects/PICDEM\ FSUSB/usb_descriptors.o Objects/PICDEM\ FSUSB/main.o Objects/PICDEM\ FSUSB/usb_device.o Objects/PICDEM\ FSUSB/usb_function_hid.o Objects/PICDEM\ FSUSB/i2c.o Objects/PICDEM\ FSUSB/ks108.o Objects/PICDEM\ FSUSB/eeprom.o
	$(LD) /p18F4550 /l"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\USB\HID Device Driver" /l"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\USB" /l"C:\mcc18\lib" /k"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip" "rm18f4550 - HID Bootload.lkr" "Objects\PICDEM FSUSB\usb_descriptors.o" "Objects\PICDEM FSUSB\main.o" "Objects\PICDEM FSUSB\usb_device.o" "Objects\PICDEM FSUSB\usb_function_hid.o" "Objects\PICDEM FSUSB\i2c.o" "Objects\PICDEM FSUSB\ks108.o" "Objects\PICDEM FSUSB\eeprom.o" /u_CRUNTIME /z__MPLAB_BUILD=1 /m"psygsr.map" /w /o"psygsr.cof"

Objects/PICDEM\ FSUSB/usb_descriptors.o : usb_descriptors.c ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdio.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdlib.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/string.h ../Microchip/Include/USB/usb_common.h ../Microchip/Include/USB/usb_device.h ../Microchip/Include/USB/usb_hal.h usb_descriptors.c ../Microchip/Include/USB/usb.h ../Microchip/Include/GenericTypeDefs.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stddef.h ../Microchip/Include/Compiler.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18cxxx.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18f4550.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdarg.h usb_config.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/limits.h ../Microchip/Include/USB/usb_ch9.h ../Microchip/Include/USB/usb_hal_pic18.h ../Microchip/Include/USB/usb_function_hid.h
	$(CC) -p=18F4550 /i"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include" -I"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include\USB" -I"." -I"C:\MCC18\h" "usb_descriptors.c" -fo=".\Objects\PICDEM FSUSB\usb_descriptors.o" -pa=4

Objects/PICDEM\ FSUSB/main.o : main.c ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdio.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdlib.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/string.h ../Microchip/Include/USB/usb_common.h ../Microchip/Include/USB/usb_device.h ../Microchip/Include/USB/usb_hal.h font.h ks108.h eeprom.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/i2c.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/sw_i2c.h main.c ../Microchip/Include/USB/usb.h ../Microchip/Include/GenericTypeDefs.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stddef.h ../Microchip/Include/Compiler.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18cxxx.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18f4550.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdarg.h usb_config.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/limits.h ../Microchip/Include/USB/usb_ch9.h ../Microchip/Include/USB/usb_hal_pic18.h HardwareProfile.h HardwareProfile\ -\ PICDEM\ FSUSB.h ../Microchip/Include/USB/usb_function_hid.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/pconfig.h
	$(CC) -p=18F4550 /i"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include" -I"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include\USB" -I"." -I"C:\MCC18\h" "main.c" -fo=".\Objects\PICDEM FSUSB\main.o" -pa=4

Objects/PICDEM\ FSUSB/usb_device.o : ../Microchip/USB/usb_device.c ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdio.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdlib.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/string.h ../Microchip/Include/USB/usb_common.h ../Microchip/Include/USB/usb_device.h ../Microchip/Include/USB/usb_hal.h ../Microchip/USB/usb_device.c ../Microchip/Include/USB/usb.h ../Microchip/Include/GenericTypeDefs.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stddef.h ../Microchip/Include/Compiler.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18cxxx.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18f4550.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdarg.h usb_config.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/limits.h ../Microchip/Include/USB/usb_ch9.h ../Microchip/Include/USB/usb_hal_pic18.h HardwareProfile.h HardwareProfile\ -\ PICDEM\ FSUSB.h ../Microchip/USB/usb_device_local.h
	$(CC) -p=18F4550 /i"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include" -I"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include\USB" -I"." -I"C:\MCC18\h" "C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\USB\usb_device.c" -fo=".\Objects\PICDEM FSUSB\usb_device.o" -pa=4

Objects/PICDEM\ FSUSB/usb_function_hid.o : ../Microchip/USB/HID\ Device\ Driver/usb_function_hid.c ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdio.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdlib.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/string.h ../Microchip/Include/USB/usb_common.h ../Microchip/Include/USB/usb_device.h ../Microchip/Include/USB/usb_hal.h ../Microchip/USB/HID\ Device\ Driver/usb_function_hid.c ../Microchip/Include/GenericTypeDefs.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stddef.h ../Microchip/Include/Compiler.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18cxxx.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18f4550.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/stdarg.h ../Microchip/Include/USB/usb.h usb_config.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/limits.h ../Microchip/Include/USB/usb_ch9.h ../Microchip/Include/USB/usb_hal_pic18.h ../Microchip/Include/USB/usb_function_hid.h
	$(CC) -p=18F4550 /i"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include" -I"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include\USB" -I"." -I"C:\MCC18\h" "C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\USB\HID Device Driver\usb_function_hid.c" -fo=".\Objects\PICDEM FSUSB\usb_function_hid.o" -pa=4

Objects/PICDEM\ FSUSB/i2c.o : i2c.c ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/i2c.h AN991.h ks108.h i2c.c ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/pconfig.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18cxxx.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18f4550.h
	$(CC) -p=18F4550 /i"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include" -I"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include\USB" -I"." -I"C:\MCC18\h" "i2c.c" -fo=".\Objects\PICDEM FSUSB\i2c.o" -pa=4

Objects/PICDEM\ FSUSB/ks108.o : ../glcd/ks108.c ../glcd/ks108.h ../glcd/ks108.c ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18cxxx.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18f4550.h
	$(CC) -p=18F4550 /i"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include" -I"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include\USB" -I"." -I"C:\MCC18\h" "C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\glcd\ks108.c" -fo=".\Objects\PICDEM FSUSB\ks108.o" -pa=4

Objects/PICDEM\ FSUSB/eeprom.o : eeprom.c eeprom.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/i2c.h i2c_extras.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/sw_i2c.h eeprom.c ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/pconfig.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18cxxx.h ../../../../../../Program\ Files/Microchip/mplabc18/v3.40/h/p18f4550.h
	$(CC) -p=18F4550 /i"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include" -I"C:\Documents and Settings\andras\My Documents\ANDRAS_HW\Microchip-projects\Microchip\Include\USB" -I"." -I"C:\MCC18\h" "eeprom.c" -fo=".\Objects\PICDEM FSUSB\eeprom.o" -pa=4

clean : 
	$(RM) "Objects\PICDEM FSUSB\usb_descriptors.o" "Objects\PICDEM FSUSB\main.o" "Objects\PICDEM FSUSB\usb_device.o" "Objects\PICDEM FSUSB\usb_function_hid.o" "Objects\PICDEM FSUSB\i2c.o" "Objects\PICDEM FSUSB\ks108.o" "Objects\PICDEM FSUSB\eeprom.o" "psygsr.cof" "psygsr.hex" "psygsr.map"

